version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "github_actions"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(deps)"
    groups:
      github-actions-maintenance:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "America/Los_Angeles"
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "python:uv"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(deps)"
    groups:
      backend-maintenance:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(deps)"
    groups:
      docker-maintenance:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "javascript"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(deps)"
    groups:
      frontend-maintenance:
        patterns:
          - "*"
