export const EVIDENCE_STORAGE_KEY = "dealwatch.compare.savedEvidencePackages";
export const MAX_SAVED_EVIDENCE_PACKAGES = 12;
export const STRONG_MATCH_SCORE = 85;
export const REVIEW_MATCH_SCORE = 70;

export const defaultUrls = [
  "https://www.sayweee.com/zh/product/Asian-Honey-Pears-3ct/5869",
  "https://www.99ranch.com/product-details/1615424/8899/078895126389",
  "https://www.target.com/p/utz-ripples-original-potato-chips-7-75oz/-/A-13202943",
].join("\n");

export type DraftMessage = { en: string; "zh-CN"?: string };

export const COMPARE_COPY = {
  form: {
    errors: {
      zipRequired: { en: "ZIP code is required.", },
      invalidProductUrl: { en: "Each line must be a valid product URL.", },
      minUrls: { en: "Enter at least two product URLs.", },
      maxUrls: { en: "Enter no more than ten product URLs.", },
    },
  },
  decision: {
    noResolvedCandidate: { en: "No resolved candidate", },
    noConfidentPair: { en: "No confident pair yet", },
    riskUnsupported: { en: "{{count}} submitted URL{{plural}} did not map to a supported store path.", },
    riskStoreDisabled: { en: "{{count}} row{{plural}} belongs to a store that is currently disabled in runtime settings.", },
    riskFetchFailed: { en: "{{count}} supported row{{plural}} still failed to fetch live offer evidence.", },
    riskNoPairScore: { en: "Multiple rows resolved, but none of them produced a pairwise compare score yet.", },
    riskWeakStrongest: { en: "The strongest pair is only {{score}}, so the rows may still describe different products.", },
    riskNeedTwoCandidates: { en: "A compare-aware watch group needs at least two group-ready candidates.", },
    riskLowerConfidence: { en: "{{count}} lower-confidence pair{{plural}} still deserve a quick human review before you trust the basket.", },
    riskNoBlocker: { en: "No obvious compare blocker surfaced in this preview, but the final decision still belongs to the operator.", },
    state: {
      noDecisionHeadline: { en: "No durable decision yet", },
      noDecisionSummary: { en: "Nothing resolved into a reusable candidate, so this compare run should stay in review instead of creating watch state.", },
      noDecisionAction: { en: "Fix the unsupported or fetch-failed rows before you create any watch task or watch group.", },
      oneCandidateHeadline: { en: "One candidate is usable, but the compare basket is incomplete", },
      oneCandidateSummary: { en: "{{bestCandidateLabel}} is the only row with durable evidence right now, so there is no honest cross-store winner yet.", },
      oneCandidateAction: { en: "Create a single watch task only if this row already looks correct; otherwise gather more evidence first.", },
      strongHeadline: { en: "This compare run is strong enough for a watch group", },
      strongSummary: { en: "{{bestCandidateLabel}} currently looks like the clearest low-price row, and {{bestMatchLabel}} already forms a strong compare pair.", },
      strongAction: { en: "Save the evidence package, then create a compare-aware watch group so the runtime can keep reranking instead of freezing one URL forever.", },
      reviewHeadline: { en: "The basket is promising, but the decision still needs review", },
      reviewSummary: { en: "{{bestCandidateLabel}} looks usable and {{bestMatchLabel}} is plausible, but the why-like / why-unlike notes still matter before you lock durable group state.", },
      reviewAction: { en: "Review the evidence pair details, then decide whether this should become a watch group or stay as a single-task handoff.", },
      mixedHeadline: { en: "The compare result is mixed and should stay in review", },
      mixedSummary: { en: "{{bestCandidateLabel}} is still the clearest row, but the strongest pair is weak enough that a group could hide real product mismatch risk.", },
      mixedAction: { en: "Keep this as evidence only, or create a single watch task from the clearest row after a manual check.", },
    },
    badge: {
      groupReady: { en: "group-ready", },
      review: { en: "review", },
      hold: { en: "hold", },
      info: { en: "info", },
    },
    stats: {
      resolved: { en: "Resolved", },
      groupReady: { en: "Group-ready", },
      bestListed: { en: "Best listed", },
      strongestPair: { en: "Strongest pair", },
      aiTitle: { en: "AI-assisted explanation", },
      aiNote: { en: "The deterministic decision board stays primary. This card is only the explain layer on top of that evidence.", },
      riskNotes: { en: "{{count}} note{{plural}}", },
      unsupported: { en: "Unsupported", },
      fetchFailures: { en: "Fetch failures", },
    },
    ai: {
      badge: {
        ok: { en: "available", },
        disabled: { en: "disabled", },
        error: { en: "error", },
        skipped: { en: "skipped", },
        unavailable: { en: "unavailable", },
      },
      headline: {
        ok: { en: "AI-assisted explanation", },
        disabled: { en: "AI assistance is disabled", },
        error: { en: "AI-assisted explanation hit an error", },
        skipped: { en: "AI-assisted explanation was skipped", },
        unavailable: { en: "AI-assisted explanation unavailable", },
      },
      summary: {
        disabled: {
          en: "AI assistance is disabled for this workspace. The decision board, risk summary, and pair evidence remain the source of truth.",
        },
        error: {
          en: "AI-assisted explanation could not be generated for this compare run. Review the deterministic summary and pair evidence instead.",
        },
        skipped: {
          en: "AI-assisted explanation was skipped for this compare run. The deterministic summary and pair evidence still tell the full story.",
        },
        unavailable: {
          en: "AI-assisted explanation unavailable. Showing deterministic summary and evidence only.",
        },
      },
    },
  },
  recommendation: {
    eyebrow: { en: "Recommendation", },
    basisTitle: { en: "Basis", },
    uncertaintyTitle: { en: "Uncertainty", },
    evidenceRefsTitle: { en: "Evidence refs", },
    whyAbstained: { en: "Why this recommendation abstained", },
    verdict: {
      wait: { en: "Keep watching", },
      recheck_later: { en: "Re-check later", },
      insufficient_evidence: { en: "Not enough evidence yet", },
    },
  },
  saved: {
    labelWithTitle: { en: "{{title}} · ZIP {{zipCode}}", },
    labelFallback: { en: "Compare evidence · ZIP {{zipCode}}", },
    shareTitle: { en: "DealWatch compare evidence package", },
    shareLabel: { en: "Label: {{value}}", },
    shareSavedAt: { en: "Saved at: {{value}}", },
    shareZip: { en: "ZIP: {{value}}", },
    shareSubmitted: { en: "Submitted URLs: {{value}}", },
    shareResolved: { en: "Resolved candidates: {{value}}", },
    shareDecision: { en: "Decision summary: {{value}}", },
    shareRisk: { en: "Risk summary: {{value}}", },
    shareAction: { en: "Recommended action: {{value}}", },
    shareRuntimeReady: { en: "Runtime review: {{value}}", },
    shareRuntimeMissing: { en: "Runtime review: not created", },
  },
  notices: {
    invalidCompare: { en: "Invalid compare request.", },
    compareFailed: { en: "Failed to compare these product URLs.", },
    saveLocal: { en: "Saved this compare evidence package for local review on this machine.", },
    runtimeCreated: { en: "Runtime evidence package created. This stays local to the runtime and does not create a public link.", },
    runtimeFailed: { en: "Failed to create the runtime evidence package.", },
    copiedSummary: { en: "Copied the compare evidence summary. It describes the evidence package without pretending there is a public share link.", },
    clipboardFailed: { en: "Clipboard access failed. Save the package first and review it locally instead.", },
    invalidGroup: { en: "Invalid watch group configuration.", },
    needTwoCandidates: { en: "At least two successful compare candidates are required to create a watch group.", },
    createGroupFailed: { en: "Failed to create the watch group from compare candidates.", },
  },
  savedPanel: {
    savedPackagesBadge: { en: "{{count}} saved package{{plural}}", },
    runtimeBacked: { en: "runtime-backed", },
    localOnly: { en: "local-only", },
    savedAt: { en: "Saved {{value}}", },
    runtimeReady: { en: "runtime package ready", },
    localReviewOnly: { en: "local review only", },
    detailSummary: {
      en: "Use a saved package when you want the compare conclusion to stay reviewable on this machine before you turn it into longer-lived runtime evidence.",
    },
    zip: { en: "ZIP", },
    submitted: { en: "Submitted", },
    resolved: { en: "Resolved", },
    decisionSummary: { en: "Decision summary", },
    riskSummary: { en: "Risk summary", },
    copySavedSummary: { en: "Copy saved summary", },
    openRuntimePackageView: { en: "Open runtime package view", },
  },
  candidatePanel: {
    submittedBadge: { en: "{{count}} submitted", },
    resolvedBadge: { en: "{{count}} resolved", },
    groupReadyBadge: { en: "{{count}} group-ready candidates", },
    intro: {
      en: "Once a row looks right, you can either carry one candidate into a single watch task, or keep several strong rows together in a compare-aware watch group.",
    },
    fetched: { en: "fetched", },
    fetchFailed: { en: "fetch failed", },
    unsupported: { en: "limited support", },
    storeDisabled: { en: "store disabled", },
    unknownStore: { en: "unknown-store", },
    matchScore: { en: "match score {{value}}", },
    tier: {
      officialFull: { en: "official full", },
      officialPartial: { en: "official partial", },
      officialInProgress: { en: "official in progress", },
      limitedUnofficial: { en: "limited unofficial", },
    },
    fetchedSummary: {
      en: "This row has enough live offer evidence to move into the watch flow.",
    },
    officialFullSummary: {
      en: "This row is on the full official store path. Compare, single-watch, compare-aware watch group, recovery, and cashback all sit inside the current repo-local product flow.",
    },
    officialPartialSummary: {
      en: "This row is on an official partial store path. Compare intake is real, but some broader store capabilities are still intentionally deferred.",
    },
    fetchFailedSummary: {
      en: "The URL is supported, but the fetch still failed, so this row should not drive a durable decision yet.",
    },
    unsupportedSummary: {
      en: "This URL did not resolve into a supported compare target.",
    },
    unsupportedHostSummary: {
      en: "This host is not in the official registry yet. DealWatch can keep it in compare review and repo-local evidence, but not as live watch state.",
    },
    unsupportedPathSummary: {
      en: "The store host is recognized, but this URL shape is not an officially supported product path yet.",
    },
    storeDisabledSummary: {
      en: "The store exists in the official registry, but its runtime binding is disabled, so this row stays evidence-only for now.",
    },
    listed: { en: "Listed", },
    evidenceNotes: { en: "Evidence notes", },
    brand: { en: "Brand {{value}}. ", },
    size: { en: "Size {{value}}. ", },
    originalPrice: { en: "Original {{value}}.", },
    noOriginalPrice: { en: "No original-price evidence returned.", },
    submittedUrl: { en: "Submitted URL", },
    normalizedUrl: { en: "Normalized URL", },
    errorCode: { en: "Error: {{value}}", },
    recommendedCta: { en: "Recommended CTA", },
    recommendedCtaSummary: {
      en: "Use this when you want to turn one confirmed row into a watch task without carrying the whole basket forward.",
    },
    createWatchTaskFromRow: { en: "Create watch task from this row", },
    evidenceFingerprint: { en: "Evidence fingerprint", },
    noDurableCta: {
      en: "No durable CTA yet. This row needs a successful fetch before it can become a watch task or count toward a group.",
    },
    nextStep: { en: "Next step: {{value}}", },
    stillAllowed: { en: "Still allowed", },
    stillBlocked: { en: "Still blocked", },
    saveCompareEvidence: { en: "save compare evidence", },
    createWatchTaskAction: { en: "create watch task", },
    createWatchGroupAction: { en: "create watch group", },
    cashbackAction: { en: "cashback context", },
    notificationsAction: { en: "notifications", },
    missingCapabilities: { en: "Missing capabilities", },
  },
  groupBuilder: {
    eyebrow: { en: "Create watch group", },
    title: { en: "Turn the strongest rows into one decision basket", },
    summary: {
      en: "A watch group is the product answer to \"don't forget the alternatives.\" Instead of freezing one URL forever, the runtime can keep reevaluating the basket each time it runs.",
    },
    groupTitle: { en: "Group title", },
    zipCode: { en: "ZIP Code", },
    cadenceMinutes: { en: "Cadence (minutes)", },
    thresholdType: { en: "Threshold Type", },
    thresholdPriceBelow: { en: "Price below", },
    thresholdDropPercent: { en: "Price drop percent", },
    thresholdEffectiveBelow: { en: "Effective price below", },
    thresholdValue: { en: "Threshold Value", },
    thresholdHelp: {
      en: "Suggested from the best currently fetched candidate so you start from real compare evidence.",
    },
    cooldownMinutes: { en: "Cooldown (minutes)", },
    recipientEmail: { en: "Recipient Email", },
    enableNotifications: { en: "Enable notifications for this group", },
    rowsEnteringBasket: { en: "Rows that will enter the basket", },
    listedAtStore: { en: "{{storeKey}} · listed {{value}}", },
    similarity: { en: "similarity {{value}}", },
    noSuccessfulCandidates: {
      en: "No successful compare candidates are available yet, so group creation stays locked.",
    },
    lockedHint: {
      en: "A compare-aware group stays locked until at least two successful candidates survive the preview. That keeps a thin basket from pretending it is durable compare truth.",
    },
    creating: { en: "Creating watch group from compare candidates...", },
    createButton: { en: "Create watch group from successful candidates", },
    defaultTitleSuffix: { en: "compare group", },
    errors: {
      titleTooLong: { en: "Group title must stay within 120 characters.", },
      zipRequired: { en: "ZIP code is required.", },
      cadenceMin: { en: "Cadence must be at least 5 minutes.", },
      cadenceMax: { en: "Cadence must stay within 10080 minutes.", },
      thresholdValueMin: { en: "Threshold value must be zero or above.", },
      cooldownMin: { en: "Cooldown must be zero or above.", },
      cooldownMax: { en: "Cooldown must stay within 10080 minutes.", },
      recipientEmailRequired: { en: "Recipient email is required.", },
    },
  },
  pairEvidence: {
    title: { en: "Pair evidence", },
    summary: {
      en: "These scores are the pair-by-pair proof. They explain why two rows look close, and why a row might still stay out of the basket.",
    },
    strong: { en: "strong", },
    review: { en: "review", },
    weak: { en: "weak", },
    titleSimilarity: { en: "Title {{value}}", },
    brand: { en: "brand: {{value}}", },
    size: { en: "size: {{value}}", },
    keys: { en: "keys: {{value}}", },
    versus: { en: "vs", },
    unknown: { en: "unknown", },
    whyClose: { en: "Why this looks close", },
    whyDiffer: { en: "Why this may differ", },
    noPairScore: { en: "No successful pair produced a match score.", },
  },
} as const;

export const COMPARE_CAPABILITY_COPY = {
  officialStoreRegistry: { en: "official store registry", },
  manifestEntry: { en: "store manifest entry", },
  compareIntake: { en: "compare intake", },
  watchTask: { en: "watch task", },
  watchGroup: { en: "watch group", },
  recovery: { en: "recovery", },
  cashback: { en: "cashback", },
} as const;
